import { cookies, headers } from "next/headers";
import { postgres } from "./postgres";
const COOKIE="ta_session";
export type StandaloneUser={id:string;email:string;displayName:string;organizationId:string;role:string};
const hex=(bytes:ArrayBuffer|Uint8Array)=>[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("");
async function sha256(value:string){return hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));}
async function derive(password:string,salt:Uint8Array,iterations=210000){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const stableSalt=new Uint8Array(salt);return hex(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:stableSalt.buffer,iterations},key,256));}
export async function passwordHash(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));return `pbkdf2-sha256$210000$${hex(salt)}$${await derive(password,salt)}`;}
export async function verifyPassword(password:string,stored:string){const [kind,count,saltHex,expected]=stored.split("$");if(kind!=="pbkdf2-sha256"||!expected)return false;const salt=Uint8Array.from(saltHex.match(/.{2}/g)||[],x=>parseInt(x,16));const actual=await derive(password,salt,Number(count));if(actual.length!==expected.length)return false;let different=0;for(let i=0;i<actual.length;i++)different|=actual.charCodeAt(i)^expected.charCodeAt(i);return different===0;}
export async function currentStandaloneUser():Promise<StandaloneUser|null>{if(!process.env.DATABASE_URL)return null;const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;const rows=await postgres()`SELECT u.id,u.email,u.display_name,m.organization_id,m.role FROM sessions s JOIN users u ON u.id=s.user_id JOIN organization_memberships m ON m.user_id=u.id AND m.organization_id=s.organization_id WHERE s.id_hash=${await sha256(token)} AND s.revoked_at IS NULL AND s.expires_at>now() AND u.status='active' LIMIT 1`;const row=rows[0] as Record<string,string>|undefined;return row?{id:row.id,email:row.email,displayName:row.display_name,organizationId:row.organization_id,role:row.role}:null;}
export async function createSession(userId:string,organizationId:string){const token=hex(crypto.getRandomValues(new Uint8Array(32)));const h=await headers();await postgres()`INSERT INTO sessions(id_hash,user_id,organization_id,expires_at,user_agent) VALUES (${await sha256(token)},${userId},${organizationId},now()+interval '12 hours',${h.get("user-agent")?.slice(0,500)||null})`;(await cookies()).set(COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:43200});}
export async function revokeSession(){const jar=await cookies();const token=jar.get(COOKIE)?.value;if(token&&process.env.DATABASE_URL)await postgres()`UPDATE sessions SET revoked_at=now() WHERE id_hash=${await sha256(token)}`;jar.delete(COOKIE);}
