import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const tasks = sqliteTable("tasks", {
  id: text("id").primaryKey(), title: text("title").notNull(), description: text("description").notNull(),
  agentId: text("agent_id").notNull(), priority: text("priority").notNull(), status: text("status").notNull(),
  dueDate: text("due_date"), integration: text("integration"), approvalRequired: integer("approval_required").notNull().default(0),
  createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull(),
});
export const memories = sqliteTable("memories", { id: text("id").primaryKey(), category: text("category").notNull(), content: text("content").notNull(), approved: integer("approved").notNull().default(1), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() });
export const approvals = sqliteTable("approvals", { id: text("id").primaryKey(), agentId: text("agent_id").notNull(), actionType: text("action_type").notNull(), summary: text("summary").notNull(), reason: text("reason").notNull(), exactChange: text("exact_change").notNull(), targetPlatform: text("target_platform").notNull(), payload: text("payload").notNull(), status: text("status").notNull(), executionResult: text("execution_result"), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() });
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), conversationId: text("conversation_id"), agentId: text("agent_id").notNull(), role: text("role").notNull(), message: text("message").notNull(), status: text("status").notNull().default("ready"), createdAt: text("created_at").notNull() });
export const integrations = sqliteTable("integrations", { id: text("id").primaryKey(), name: text("name").notNull(), status: text("status").notNull(), explanation: text("explanation").notNull(), capabilities: text("capabilities").notNull(), lastChecked: text("last_checked") });
export const activity = sqliteTable("activity", { id: text("id").primaryKey(), agentId: text("agent_id").notNull(), event: text("event").notNull(), detail: text("detail").notNull(), createdAt: text("created_at").notNull() });
export const integrationConnections = sqliteTable("integration_connections", { id: text("id").primaryKey(), provider: text("provider").notNull().unique(), accountLabel: text("account_label").notNull(), encryptedToken: text("encrypted_token").notNull(), scopes: text("scopes").notNull(), status: text("status").notNull(), connectedAt: text("connected_at").notNull(), lastChecked: text("last_checked") });
export const oauthStates = sqliteTable("oauth_states", { id: text("id").primaryKey(), provider: text("provider").notNull(), stateHash: text("state_hash").notNull().unique(), accountLabel: text("account_label").notNull(), expiresAt: text("expires_at").notNull(), usedAt: text("used_at") });
export const mediaAttachments = sqliteTable("media_attachments", { id: text("id").primaryKey(), contextType: text("context_type").notNull(), contextId: text("context_id").notNull(), objectKey: text("object_key").notNull().unique(), fileName: text("file_name").notNull(), mimeType: text("mime_type").notNull(), sizeBytes: integer("size_bytes").notNull(), source: text("source").notNull().default("uploaded"), createdAt: text("created_at").notNull() });
